version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout  # checkout source code to working directory
      - run:
          # run pytest
          name: pytest
          command: |  
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements_dev.txt
            python3 -m pytest tests/
      - run:
          # build package
          name: build module
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel
            ls
      - run:
          # test package
          name: test module
          command: |
            . venv/bin/activate
            pip install dist/article_api_test-1.0.0-py3-none-any.whl
#            article-api --url "https://www.bbc.com/news/science-environment-61383391"
      - when:
          condition:
            equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                # publish to internal pypi
                name: publish to internal pypi
                command: |
                  . venv/bin/activate
                  set -x
                  aws s3 sync dist/ s3://pkgrepo.scrapinghub.com/python/packages/
            
